[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#98cbfe"
cyan = "#75daa9"
green = "#a3d572"
magenta = "#e5b0ff"
red = "#ffa7da"
white = "#ffffff"
yellow = "#efbd8b"

[colors.normal]
black = "#303030"
blue = "#6095c5"
cyan = "#3ba275"
green = "#6d9e3f"
magenta = "#ac7bde"
red = "#d370a3"
white = "#cfcfcf"
yellow = "#b58858"

[colors.primary]
background = "#232323"
foreground = "#a0a0a0"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Iosevka"

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[[hints.enabled]]
regex = "(?-u:\\b)perf-\\d{4}(-\\w+)*(?-u:\\b)"
action = "Paste"
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(?-u:\\b)([\\w-]+([\\./][\\w-]+)+)(?-u:\\b)"
action = "Paste"
binding = { key = "F", mods = "Shift|Alt" }
